Prediction Assignment Writeup
========================================================

The task was to design a model to predict the acitivity being carried out based on sensor data from Human activity trackers


```{r}
library(caret)
#read trainning data and remove missing values
inTrainData <- read.csv("pml-training.csv",na.strings=c("NA",""))
missingVals<-apply(inTrainData,2, function (x) {sum (is.na(x))})
tr_temp<-inTrainData[,missingVals==0]
trainDataFull<-tr_temp[,-(1:7)]
#data splitting
inTrain<-createDataPartition(y=trainDataFull$classe,p=0.7,list=FALSE)
trainData<-trainDataFull[inTrain,]
cvData<-trainDataFull[-inTrain,]
```
### The model
Random Forests model.
```{r}
model<-train(trainData[,-53],trainData$classe,method="rf",trControl=trainControl(method="oob",number=4,allowParallel=TRUE))
model
```

#### Cross Validation
An estimate of the out-of-sample error.
```{r}
cvAns<-predict(model,cvData[,-53])
numCorrect<-sum(cvAns==cvData[,53])
1-numCorrect/length(cvAns)
```

### Prediction Code
```{r}
pmlTest <- read.csv("pml-testing.csv", na.strings=c("NA",""))
testData<-pmlTest[,names(pmlTest)%in%names(trainDataFull)]
answers<-predict(model,testData)
answers
```
